<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(NetCoreAppCurrent)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="System\IO\ReadOnlyMemoryCharStream.cs" />
    <Compile Include="System\IO\MemoryTStream.cs" />
    <Compile Include="System\IO\ReadOnlySequenceStream.cs" />
    <Compile Include="System\IO\StringStream.cs" />
    <Compile Include="System\IO\StreamFactory.cs" />
  </ItemGroup>

</Project>
