<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetCoreAppCurrent)</TargetFramework>
    <Nullable>enable</Nullable>
    <EnableDefaultItems>true</EnableDefaultItems>
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
    <EnableAotAnalyzer>false</EnableAotAnalyzer>
    <NoWarn>$(NoWarn);CA2007;CS1591;CA1050;CA1515</NoWarn>
    <DocumentationFile></DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(LibrariesProjectRoot)System.ComponentModel.Annotations\src\System.ComponentModel.Annotations.csproj" />
    <ProjectReference Include="$(LibrariesProjectRoot)System.Runtime\src\System.Runtime.csproj" />
  </ItemGroup>

</Project>
